FRONTENDSCHOOL5/final-04-fearless4

src/components/button/button.style.jsx
src/components/form/form.style.jsx
src/pages/loginEmail/LoginEmail.jsx
src/pages/loginEmail/loginEmail.style.jsx
src/routes/Router.jsx

button 폴더 안 button style 컴포넌트에 LoginButton style 추가, form 폴더 생성 및 폴더 안 form style 컴포넌트 생성,
loginEmail 페이지 생성

Docs: Login - email 페이지 마크업 마이그레이션 진행

---

src/pages/loginEmail/Signup.jsx
src/pages/signup/signup.style.jsx
src/routes/Router.jsx

Docs : signup 페이지 마크업 마이그레이션

---

src/components/button/button.style.jsx
src/pages/loginEmail/LoginEmail.jsx
src/pages/loginEmail/loginEmail.style.jsx

정규식 패턴을 사용하여 이메일과 비밀번호의 유효성 검사 기능 추가 - 이메일 형식지키지 않을 경우 다시 입력하도록 함, 
없는 이메일이나 비밀번호에 대한 경고 문구 추가 - 없는 사용자일 경우 다시 입력하도록 함, API를 이용해 로그인 기능을 구현,
button style 컴포넌트에 있는 LoginButton에 opacity 및 cursor 기능 추가 및 loginEmail style 컴포넌트에 SignUpContainer cursor 기능 추가 - 사용자 경험 개선하기 위함

Feat: LoginEmail 페이지 기능 추가

---

src/markup/product.css
src/markup/product.html
src/pages/loginEmail/LoginEmail.jsx

Docs: product 페이지 마크업

---

src/components/button/button.style.jsx
src/pages/product/Product.jsx
src/pages/product/product.style.jsx
src/routes/Router.jsx

pages 폴더 안에 product 페이지 생성하여 React JSX 문법과 styled-components을 사용하여 마이그레이션 
button 폴더 안 button style 컴포넌트 안에 SaveButton style 추가 
routes 폴더에 product 페이지 추가

Docs: product 페이지 마크업 마이그레이션 진행

---

src/pages/userProfile/ProductsForSale.jsx
src/pages/userProfile/productsForSale.style.jsx

product 페이지에 등록된 상품이 있는 경우, 그 목록을 가져와서 동적으로 상품 목록을 생성(API 활용)
상품 가격은 원단위로 변환하여 표시

Feat: 등록된 상품 정보를 가져와서 판매 중인 상품 섹션에 보이게 하는 기능 추가

---

src/pages/userProfile/MyProfile.jsx
src/pages/userProfile/UserProfile.jsx
src/pages/userProfile/userProfile.style.jsx

Feat: 각 Profile 페이지에 ProductForSale 컴포넌트 추가

Feat: 각 Profile 페이지에 ProductForSale 컴포넌트 추가

---

src/pages/product/Product.jsx
src/pages/userProfile/MyProfile.jsx
src/pages/userProfile/ProductsForSale.jsx
src/pages/userProfile/ProductsForSaleEdit.jsx
src/routes/Router.jsx

Chore: Router.jsx에서 ProductsForSaleEdit 페이지 연결
Feat: MyProfile 페이지 상품 등록 버튼 및 Product 페이지 화살표 클릭 시 페이지 이동 기능 추가 
Feat, Fix: 선택된 상품 수정 기능 추가, 본인 여부에 따른 모달창 구성 수정

Products for sale

---

src/pages/follow/Followings.jsx
src/pages/userProfile/ProductsForSale.jsx
src/pages/userProfile/UserProfile.jsx

* fix: 팔로잉 페이지에서 팔로우 취소 버튼 눌렀을 시, 해당 유저가 사라지는 현상 수정
* Design: 유저 프로필 Padding 변경
* fix: 간헐적으로 상품 클릭시 페이지 오류나는 현상 해결

Design, fix :followPage

---

src/components/button/button.style.jsx
src/components/logo/logo.style.jsx
src/pages/login/Login.jsx
src/pages/login/login.style.jsx

- Design: login페이지에 소셜 로그인 모달 애니메이션 추가
- Design: 소셜 로그인 페이지에서 background 변경

Design: loginPage

---

src/pages/userProfile/ProductsForSale.jsx

상품을 선택하고, 삭제를 누르면 삭제를 재확인하는 모달창이 열리고, 그곳에서 삭제를 누를 때 삭제가 반영되는 기능 추가

Feat: 상품 클릭 후, 삭제 클릭 시 재확인하는 모달창 추가

---

src/components/toast/toast.style.jsx
src/pages/product/Product.jsx

SaveButton 클릭 시 상품 등록 Toast 메시지 띄우고 3초 뒤에 myProfile 페이지로 이동 기능 추가 
다른 페이지에서도 재사용할 수 있도록 components/toast 폴더 안 toast.style.jsx 생성

Feat, Docs: Toast 메시지 띄우는 기능 및 components/toast 폴더 안 toast.style.jsx 생성

---

src/components/bottomnav/bottomnav.style.jsx
src/components/modal/modal.style.jsx
src/components/navbar/navbar.style.jsx
src/components/post/post.style.jsx
src/pages/post/Comment.jsx
src/pages/post/EditPost.jsx
src/pages/post/ViewPost.jsx
src/pages/post/WritePost.jsx
src/pages/post/viewPost.style.jsx
src/pages/post/writePost.style.jsx
src/routes/Router.jsx

댓글 및 게시글 삭제, 수정, 신고 기능 구현
* Comment.jsx에서 댓글 작성자와 현재 로그인 한 사용자의 일치 여부를 비교해서 삭제 및 신고 모달 팝업 구현
* ViewPost.jsx에서 게시글 작성자와 현재 로그인 한 사용자의 일치 여부를 비교
해서 삭제 및 신고 모달 팝업 구현

[동훈] 게시글 상세 페이지 기능 구현 완료

---

src/pages/search/Search.jsx
src/pages/search/search.style.jsx

- 피드 상단에 돋보기 버튼(검색 버튼)을 클릭하면 페이지 표시
- 사용자 이름과 계정을 검색할 수 있는 페이지로, 입력창에 텍스트를 입력하면 해당하는 사용자가 나옵니다..
- 검색어와 같은 단어에는 민트색 글씨가 표시

Feat : 검색 기능 구현

---

src/pages/search/Search.jsx
src/pages/search/search.style.jsx
src/routes/Router.jsx

Refactor: 검색 페이지에 디바운스를 사용하여 렌더링 완화
Refactor: 검색페이지에 유저 잘 보이게하고, 프로필사진 눌렀을 때도 이동하도록 수정

Refactor: searchPage

---

src/pages/userProfile/ProductsForSale.jsx
src/pages/userProfile/productsForSale.style.jsx

판매자 상품명에 [추천], [할인]이 들어가 있을 경우 해당 상품만 정렬하여 보여주는 기능 추가 
추천 또는 할인상품을 보다가 전체 상품 누르면 전체 상품을 보여주는 기능 추가

Feat: 전체, 추천, 할인상품 버튼을 선택할 시 해당 요건에 맞는 상품을 정렬하여 보여주는 기능 추가

---

src/components/bottomnav/bottomnav.style.jsx
src/components/post/PostSection.jsx
src/components/post/post.style.jsx
src/pages/chat/ChatList.jsx
src/pages/follow/Followers.jsx
src/pages/follow/Followings.jsx
src/pages/login/Login.jsx
src/pages/loginEmail/LoginEmail.jsx
src/pages/loginEmail/Signup.jsx
src/pages/post/Comment.jsx
src/pages/post/ViewPost.jsx
src/pages/post/WritePost.jsx
src/pages/product/Product.jsx
src/pages/search/Search.jsx
src/pages/userProfile/MyProfile.jsx
src/pages/userProfile/MyProfileEdit.jsx
src/pages/userProfile/ProductsForSale.jsx
src/pages/userProfile/ProductsForSaleEdit.jsx
src/pages/userProfile/UserProfile.jsx
src/routes/Router.jsx

- Refactor: 모든 페이지 라우터 경로 수정, navigate는 로그인, 회원가입까지
- Refactor: 프로필, 상품, 검색, 게시글, 팔로우 페이지의 경로 수정
- Refactor: 채팅, 댓글, 게시글, 게시글 업로드 페이지 경로 수정

Refactor: MobileView 주소변경

---

src/pages/post/EditPost.jsx
src/pages/userProfile/MyProfileEdit.jsx

* 게시글 수정에서 이미지 검사 누락된 부분 추가
* 게시글 수정 navigate 경로 변경

[동훈] 이미지 유효성 검사 누락 부분 추가

---

src/pages/login/Login.jsx
src/routes/Router.jsx

Fix: Splash페이지 token 유무에 따라 렌더링할 때 깜빡이는 현상 수정

Fix: splashPage

---

package-lock.json
package.json
src/pages/chat/Chat.jsx
src/pages/chat/Chat2.jsx
src/pages/chat/ChatList.jsx
src/pages/follow/Followers.jsx
src/pages/follow/Followings.jsx
src/pages/homeFeed/Homefeed.jsx
src/pages/login/Login.jsx
src/pages/loginEmail/LoginEmail.jsx
src/pages/loginEmail/Signup.jsx
src/pages/page404/Page404.jsx
src/pages/post/EditPost.jsx
src/pages/post/ViewPost.jsx
src/pages/post/WritePost.jsx
src/pages/product/Product.jsx
src/pages/profileSetup/ProfileSetup.jsx
src/pages/search/Search.jsx
src/pages/splash/Splash.jsx
src/pages/userProfile/MyProfile.jsx
src/pages/userProfile/MyProfileEdit.jsx
src/pages/userProfile/ProductsForSaleEdit.jsx
src/pages/userProfile/UserProfile.jsx

Design: 각 페이지별로 제목 수정, 사용자가 현재 어느 페이지에 있는지 알려주기 위함

Design: Router

---

src/pages/product/Product.jsx

Fix: Product 페이지 이전 URL 유효성 검사에서는 .com이 없으면 통과하지 못해서 수정함
Feat: Product 페이지에서 setTimeout 함수의 딜레이 시간을 기존보다 짧게 수정

Product page

---

src/pages/homeFeed/homefeed.style.jsx

Design: 홈피드 게시물 날짜 잘리는 현상 수정

---

src/components/bottomnav/bottomnav.style.jsx
src/components/post/post.style.jsx
src/pages/follow/Followers.jsx
src/pages/follow/Followings.jsx
src/pages/post/Comment.jsx
src/pages/profileSetup/ProfileSetup.jsx
src/pages/search/Search.jsx
src/pages/userProfile/MyProfile.jsx
src/pages/userProfile/MyProfileEdit.jsx
src/pages/userProfile/UserProfile.jsx
src/routes/Router.jsx

- 각 프로필 페이지의 useParams로 변경하여 이전 state를 받아오지 않고 현재 페이지의 정보로 렌더링하도록 개선
- 사용자가 프로필 등록 및 수정 시 프로필 이미지를 아무것도 넣지 않았을 경우 더미 이미지 등록하도록 변경
[[Feat] 프로필 페이지 주소 변경 #106](https://github.com/FRONTENDSCHOOL5/final-04-fearless4/issues/106)
[[Feat] 프로필 등록 및 수정 시 더미 이미지 등록하도록 변경](https://github.com/FRONTENDSCHOOL5/final-04-fearless4/issues/113)
프로필과 관련된 오류가 발생 시 리뷰 부탁드립니다!

[Feat] Profile useParams 및 더미 이미지 등록

---

src/assets/icon/icon-close.svg
src/pages/product/ProductCard.jsx
src/pages/product/product.style.jsx
src/pages/product/productCard.style.jsx
src/pages/userProfile/ProductsForSale.jsx
src/pages/userProfile/productsForSale.style.jsx
src/routes/Router.jsx

- 상품 클릭시 새로운 ProductCard.jsx 뜨게 하는 기능 추가하여 사용자들이 기존보다 더 크게 상품 정보를 볼 수 있게 함
- ProductCard.jsx 부분이 추가되면서 기존 삭제/수정/웹사이트 이동 모달창을  productCard.jsx에서 OptionModalTab을 클릭할 때 뜨도록 함
[[Feat] 상품 클릭시 새로운 ProductCard.jsx 뜨게 하는 기능 추가 #126](https://github.com/FRONTENDSCHOOL5/final-04-fearless4/issues/126)
[[Refactor] productCard.jsx에서 OptionModalTab 클릭한 경우 삭제/수정/웹사이트 이동 모달창 뜨게 함 #114](https://github.com/FRONTENDSCHOOL5/final-04-fearless4/issues/114)
관련하여 오류나 추가할 사항이 필요하다고 느끼시면 말씀부탁드립니다.

Product 관련 페이지 기능 추가 및 리팩토링

---

src/api/searchApi.js
src/assets/icon/icon-search.svg
src/pages/search/Search.jsx
src/pages/search/search.style.jsx

- UI/UX 개선
- 성능 개선을 위해 더보기 버튼을 추가하여 검색 결과를 10개씩 처리
- [[Refactor] 검색페이지 리팩토링](https://github.com/FRONTENDSCHOOL5/final-04-fearless4/issues/130)
오류사항 및 개선할 부분이 있다면 피드백 부탁드립니다!

[Refactor] Search 페이지 리팩토링

---

src/api/loginApi.js
src/pages/loginEmail/LoginEmail.jsx
src/pages/loginEmail/loginEmail.style.jsx

- 로그인 페이지의 API로직을 단순화시키기 위해 axios 인스턴스 사용
- API로직을 리액트 쿼리로 변경하여 코드 간결화 및 관리하기 용이하게 변경
- 기존 div 태그를 section으로 변경함으로써 의미있는 시맨틱 태그로 수정
[[Refactor] 로그인 페이지 리팩토링](https://github.com/FRONTENDSCHOOL5/final-04-fearless4/issues/140)
해당 이슈 관련하여 오류사항 발견 시 말씀부탁드립니다!

[Refactor] 로그인 페이지 리팩토링

---

src/GlobalStyle.jsx
src/api/signupApi.js
src/components/form/form.style.jsx
src/pages/loginEmail/Signup.jsx
src/pages/search/Search.jsx
src/pages/search/search.style.jsx

- 리액트 쿼리로 변경 및 api 분리
- 유효성 검사 방식 수정
- [[Refactor] sign up 페이지 리팩토링](https://github.com/FRONTENDSCHOOL5/final-04-fearless4/issues/139)
오류사항 및 개선할 부분이 있다면 피드백 부탁드립니다!

[Refactor] sign up 페이지 리팩토링 
